resources:
    - name: dummy_resource
      type: PropertyBag
      configuration:
        key1: value1
        key2: value2
pipelines:
  - name: Run_State_Example_6
    steps:
      - name: start
        type: Bash
        execution:
          onExecute:
            - echo "Start..."

      - name: step_a
        type: Bash
        configuration:
          outputResources:
            - name: dummy_resource
          inputSteps:
            - name: start
        execution:
          onStart:
            - sleep 10
            - mkdir -p files
            - filename="${step_name}_${steplet_number}"
            - echo "I am on step ${step_name} ${steplet_number}" > ./files/$filename
          onExecute:
            - add_run_files ./files state
            - write_output dummy_resource "${step_name}_stepletId=${steplet_id}"
          onComplete:
            - echo "${step_name} Completed"

      - name: step_b
        type: Bash
        configuration:
          inputSteps:
            - name: start
          outputResources:
            - name: dummy_resource
        execution:
          onStart:
            - sleep 10
            - mkdir -p files
            - filename="${step_name}_${steplet_number}"
            - echo "I am on step ${step_name} ${steplet_number}" > ./files/$filename
          onExecute:
            - add_run_files ./files state
            - write_output dummy_resource "${step_name}_stepletId=${steplet_id}"
          onComplete:
            - echo "${step_name} Completed"

      - name: step_e
        type: Bash
        configuration:
          inputResources:
            - name: dummy_resource
        execution:
          onStart:
            - restore_run_files state ./files
            - filename="${step_name}_${steplet_number}"
            - echo "I am on step ${step_name} ${steplet_number}" > ./files/$filename
          onExecute:
            - add_run_files ./files state
          onComplete:
            - echo "${step_name} Completed"


      - name: step_f
        type: Bash
        configuration:
          inputResources:
            - name: dummy_resource
        execution:
          onStart:
            - restore_run_files state ./files
            - filename="${step_name}_${steplet_number}"
            - echo "I am on step ${step_name} ${steplet_number}" > ./files/$filename
          onExecute:
            - add_run_files ./files state
          onComplete:
            - echo "${step_name} Completed"


      - name: step_h
        type: Bash
        configuration:
          inputSteps:
            - name: step_f
            - name: step_e
        execution:
          onStart:
            - restore_run_files state ./files
            - filename="${step_name}_${steplet_number}"
            - echo "I am on step ${step_name} ${steplet_number}" > ./files/$filename
          onExecute:
            - add_run_files ./files state
          onComplete:
            - echo "${step_name} Completed"